#
# _config.yml for Google Cloud Icons
#

exclude: [ "CNAME", "**/*_src*" ]
permalink: /blog/:year/:month/:day/:title/index.:output_ext
production_url: https://gcp-icons.vectorlogo.zone
title: My Vector Icons
markdown: kramdown
plugins:
  - jekyll-redirect-from
redirect_from:
  json: false
theme: null
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

